# CI using GitHub actions

name: CI


on:
  push:
    branches:
      - main
    paths-ignore:
      - 'helm/**'
      - 'k8s/**'
      - 'README.md'

jobs:

  build:
    runs-on: self-hosted

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Go 1.22
      uses: actions/setup-go@v2
      with:
        go-version: 1.22.5

    - name: Build
      run: go build -o go-web-app

    - name: Test
      run: go test ./...
  
  code-quality:
    runs-on: self-hosted

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Go 1.22
      uses: actions/setup-go@v4
      with:
        go-version: 1.22.5

    - name: Run golangci-lint
      uses: golangci/golangci-lint-action@v6
      with:
        version: latest
  
  push:
    runs-on: self-hosted

    needs: build

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Trust self-signed cert for private registry
      run: |
        sudo mkdir -p /etc/docker/certs.d/172.25.188.203:5000
        echo "${{ secrets.REGISTRY_CRT }}" | sudo tee /etc/docker/certs.d/172.25.188.203:5000/ca.crt > /dev/null
        sudo systemctl restart docker

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Private Registry
      uses: docker/login-action@v3
      with:
        registry: 172.25.188.203:5000
        username: ${{ secrets.PRIVATE_REGISTRY_USER }}
        password: ${{ secrets.PRIVATE_REGISTRY_PASS }}

    - name: Build and Push action
      uses: docker/build-push-action@v6
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: 172.25.188.203:5000/go-web-app:${{github.run_id}}

  update-newtag-in-helm-chart:
    runs-on: self-hosted

    needs: push

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.TOKEN }}

    - name: Update tag in Helm chart
      run: |
        sed -i 's/tag: .*/tag: "${{github.run_id}}"/' helm/go-web-app-chart/values.yaml

    - name: Commit and push changes
      run: |
        git config --global user.email "gunawardhana.edu@gmail.com"
        git config --global user.name "kavinduChamithG"
        git add helm/go-web-app-chart/values.yaml
        git commit -m "Update tag in Helm chart"
        git push